### ISSUE TITLE
Example App is outdated...

### ISSUE THREAD

**Issue by benmak11** [njdehoog/Falcon#1]
The example app is outdated is is failing to run when we do the necessary pod installs... Is it possible for the example app be updated?

**Comment by njdehoog** [comment]
This project is indeed a bit old. Can you tell me specifically how it fails? Or what kind of error message you see?

**Comment by benmak11** [comment]
@njdehoog on the pod install it fails with the error message
`[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `Falcon`..`

I tried to install the Falcon cocoapod directly but the imports and methods used from that pod within the Example app fail and I am not that fluent with Objective C 😕

**Comment by njdehoog** [comment]
Thanks for clarifying @benmak11. I updated the sample app and it should run fine using the latest version of Xcode now.

Be sure to include this ATS exception in your app's info.plist, otherwise your app will crash when making an API request:

![screen shot 2016-12-27 at 10 58 35](https://cloud.githubusercontent.com/assets/1107150/21497178/8dbff080-cc23-11e6-9726-369ac6558199.png)

**Comment by benmak11** [comment]
Thanks @njdehoog! I'll try it out... Cheers
